// <auto-generated />
using APP;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APP.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200324122904_gfd")]
    partial class gfd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APP.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 150,
                            City = "Chisinau",
                            RestaurantName = "Mi Piace",
                            RestaurantType = "Italian",
                            Street = "str.Miron Costin"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 10,
                            City = "Chisinau",
                            RestaurantName = "Meat House",
                            RestaurantType = "Moldavian",
                            Street = "str.Ismail"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 50,
                            City = "Chisinau",
                            RestaurantName = "Star Kebab",
                            RestaurantType = "Fast-Food",
                            Street = "bd.Moscova"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 15,
                            City = "Chisinau",
                            RestaurantName = "Twistter",
                            RestaurantType = "Fast-Food",
                            Street = "bd.Moscova"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 50,
                            City = "Chisinau",
                            RestaurantName = "Andys Pizza",
                            RestaurantType = "Fast-Food",
                            Street = "str.Ceucari"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 150,
                            City = "Chisinau",
                            RestaurantName = "Versenz",
                            RestaurantType = "Wedding",
                            Street = "bd.Moscova"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 250,
                            City = "Chisinau",
                            RestaurantName = "Capitoles Park",
                            RestaurantType = "Wedding",
                            Street = "db.Decebal"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 70,
                            City = "Chisinau",
                            RestaurantName = "Oasis",
                            RestaurantType = "Turkish",
                            Street = "bd.Stefan cel Mare"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 150,
                            City = "Chisinau",
                            RestaurantName = "Eleganace",
                            RestaurantType = "Wedding",
                            Street = "str.Ceucari"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
